# File konfigurasi untuk Netlify

[build]
  # Direktori di mana file-file publik (seperti index.html) berada.
  # "." berarti direktori utama (root) dari proyek Anda.
  publish = "."

  # Direktori di mana Netlify akan menemukan serverless functions Anda.
  functions = "netlify/functions"

# Anda bisa menambahkan pengaturan redirect atau header di sini jika diperlukan
# Contoh:
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
